// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XYZHotel.DB;

#nullable disable

namespace XYZHotel.Migrations
{
    [DbContext(typeof(HotelsContext))]
    partial class HotelsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassLibrary.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomersCutomerId")
                        .HasColumnType("int");

                    b.Property<int?>("hotelsHotelId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("CustomersCutomerId");

                    b.HasIndex("hotelsHotelId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("ClassLibrary.Models.Customer", b =>
                {
                    b.Property<int>("CutomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CutomerId"));

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CutomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("ClassLibrary.Models.Hotels", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelId"));

                    b.Property<string>("HotelAmenities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelPrice")
                        .HasColumnType("int");

                    b.Property<int>("RoomAvailablity")
                        .HasColumnType("int");

                    b.HasKey("HotelId");

                    b.ToTable("hotels");
                });

            modelBuilder.Entity("ClassLibrary.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<int?>("hotelsHotelId")
                        .HasColumnType("int");

                    b.HasKey("RoomId");

                    b.HasIndex("hotelsHotelId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("ClassLibrary.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<int?>("HotelsHotelId")
                        .HasColumnType("int");

                    b.Property<string>("StaffName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffId");

                    b.HasIndex("HotelsHotelId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("ClassLibrary.Models.Booking", b =>
                {
                    b.HasOne("ClassLibrary.Models.Customer", "Customers")
                        .WithMany("bookings")
                        .HasForeignKey("CustomersCutomerId");

                    b.HasOne("ClassLibrary.Models.Hotels", "hotels")
                        .WithMany("Bookings")
                        .HasForeignKey("hotelsHotelId");

                    b.Navigation("Customers");

                    b.Navigation("hotels");
                });

            modelBuilder.Entity("ClassLibrary.Models.Room", b =>
                {
                    b.HasOne("ClassLibrary.Models.Hotels", "hotels")
                        .WithMany("Rooms")
                        .HasForeignKey("hotelsHotelId");

                    b.Navigation("hotels");
                });

            modelBuilder.Entity("ClassLibrary.Models.Staff", b =>
                {
                    b.HasOne("ClassLibrary.Models.Hotels", "Hotels")
                        .WithMany("Staffs")
                        .HasForeignKey("HotelsHotelId");

                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("ClassLibrary.Models.Customer", b =>
                {
                    b.Navigation("bookings");
                });

            modelBuilder.Entity("ClassLibrary.Models.Hotels", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Rooms");

                    b.Navigation("Staffs");
                });
#pragma warning restore 612, 618
        }
    }
}
